@startuml チャット

object ユーザー {
  ID
  --
  ワークスペースID(FK)
  削除日時
  作成日時
  更新日時
}

object ワークスペース {
  ID
  --
  名前
  削除日時
  作成日時
  更新日時
}

object チャンネル {
  ID
  --
  ワークスペースID(FK)
  名前
  削除日時
  作成日時
  更新日時
}

object メッセージ {
  ID
  --
  チャンネルID(FK)
  ユーザーID(FK)
  内容
  削除日時
  作成日時
  更新日時
}

object スレッドメッセージ {
  ID
  --
  チャンネルID(FK)
  メッセージID(FK)
  ユーザーID(FK)
  内容
  削除日時
  作成日時
  更新日時
}

ワークスペース --{ ユーザー
ワークスペース --o{ チャンネル
チャンネル --o{ メッセージ
メッセージ --o{ スレッドメッセージ
ユーザー --o{ メッセージ
ユーザー --o{ スレッドメッセージ
ユーザー }o--o{ チャンネル

@enduml