@startuml Penpen

object リマインダー {
  ID
  --
  登録者
  文面
  バッチ時刻
  バッチ間隔（日ごと）
  バッチ間隔（曜日）
  バッチ間隔（月ごと）
  完了日時
  削除日時
  作成日時
  更新日時
}

object バッチ {
  ID
  --
  リマインダーID(FK)
  予定日時
  実行日時
  削除日時
  作成日時
  更新日時
}

object 送信相手 {
  ID
  --
  リマインダーID(FK)
  送信相手
  削除日時
  作成日時
  更新日時
}

note right of リマインダー
使わないバッチ間隔はnull
例）3日おき9時に実行・・・バッチ時刻: 9、バッチ間隔（日ごと）: 3
end note

note right of バッチ
リマインダー作成時とバッチ実行時に次回のバッチレコードを作成
end note

リマインダー --{ バッチ
リマインダー --{ 送信相手

@enduml