@startuml ブログ

object ユーザー {
  ID
  --
  名前
  削除日時
  作成日時
  更新日時
}

object 記事 {
  ID
  --
  一世代前記事ID(FK)
  作成者ユーザーID(FK)
  更新者ユーザーID(FK)
  タイトル
  本文
  世代番号
  操作タイプ
  最新版是非
  削除日時
  作成日時
  更新日時
}

note right of 記事
追加カラム: 一世代前記事ID、世代番号、操作タイプ、最新版是非
メリット: テーブル数が少なくて済む
デメリット: 最新状態の記事一覧の表示パフォーマンスが落ちる
end note

ユーザー --o{ 記事
ユーザー --o{ 記事

@enduml