' 追加課題 --- 注文ごとに特記事項をメモできるようにして欲しい
@startuml 寿司

object セットメニューカテゴリマスタ {
  ID
  --
  名前
  削除日時
  作成日時
  更新日時
}

object セットメニューマスタ {
  ID
  --
  セットメニューカテゴリマスタID(FK)
  名前
  値段
  削除日時
  作成日時
  更新日時
}

object 皿マスタ {
  ID
  --
  名前
  値段
  削除日時
  作成日時
  更新日時
}

object 寿司マスタ {
  ID
  --
  皿マスタID(FK)
  名前
  お持ち帰り可否
  削除日時
  作成日時
  更新日時
}

object 注文 {
  ID
  --
  氏名
  電話番号
  合計金額
  税金
  支払い日時
  備考
  削除日時
  作成日時
  更新日時
}

object セットメニュー注文明細 {
  ID
  --
  注文ID(FK)
  セットメニューマスタID(FK)
  合計金額
  数量
  サビ抜きフラグ
  シャリサイズ
  削除日時
  作成日時
  更新日時
}

object 寿司注文明細 {
  ID
  --
  注文ID(FK)
  寿司マスタID(FK)
  合計金額
  数量
  サビ抜きフラグ
  シャリサイズ
  削除日時
  作成日時
  更新日時
}

セットメニューカテゴリマスタ --{ セットメニューマスタ
皿マスタ --{ 寿司マスタ
注文 --o{ セットメニュー注文明細
注文 --o{ 寿司注文明細
セットメニューマスタ --o{ セットメニュー注文明細
寿司マスタ --o{ 寿司注文明細

@enduml