@startuml ブログ

object ユーザー {
  ID
  --
  名前
  削除日時
  作成日時
  更新日時
}

object 記事 {
  ID
  --
  作成者ユーザーID(FK)
  最終更新者ユーザーID(FK)
  タイトル
  本文
  削除日時
  作成日時
  更新日時
}

object 履歴 {
  ID
  --
  記事ID(FK)
  ユーザーID(FK)
  タイトル
  本文
  世代番号
  操作タイプ
  削除日時
  作成日時
  更新日時
}

note right of 履歴
世代番号は採番済みのもの+1を新たな世代番号として採番する。
更新後のタイトル、本文を保持する。
操作タイプには、作成（・参照）・更新・削除を記録する
end note

ユーザー --o{ 記事
ユーザー --o{ 記事
ユーザー --o{ 履歴
記事 --o{ 履歴

@enduml