@startuml ドキュメント

object ユーザー {
  ID
  --
  削除日時
  作成日時
  更新日時
}

object ディレクトリ {
  ID
  --
  ディレクトリ名
  親ディレクトリID(FK)
  削除日時
  作成日時
  更新日時
}

object ドキュメント {
  ID
  --
  ディレクトリID(FK)
  ドキュメント名
  テキスト
  削除日時
  作成日時
  更新日時
}

object ディレクトリ履歴 {
  ID
  --
  ディレクトリID(FK)
  ユーザーID(FK)
  世代番号
  ディレクトリ名
  操作タイプ
  削除日時
  作成日時
  更新日時
}

object ドキュメント履歴 {
  ID
  --
  ドキュメントID(FK)
  ユーザーID(FK)
  世代番号
  ドキュメント名
  テキスト
  操作タイプ
  削除日時
  作成日時
  更新日時
}

note right of ドキュメント履歴
世代番号は採番済みのもの+1を新たな世代番号として採番する。
更新後のドキュメント名、テキストを保持する。
操作タイプには、作成（・参照）・更新・削除を記録する。
end note

ディレクトリ --o{ ディレクトリ
ディレクトリ --o{ ドキュメント
ディレクトリ --{ ディレクトリ履歴
ユーザー --o{ ディレクトリ履歴
ドキュメント --{ ドキュメント履歴
ユーザー --o{ ドキュメント履歴

@enduml